sudo: false
before_script:
- curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git cobalt-org/cobalt.rs
  --crate cobalt --force --target x86_64-unknown-linux-gnu --tag v0.15.0
- export PATH="$PATH:~/.cargo/bin"
script:
- cobalt build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: build
  target_branch: master
  on:
    branch: source
env:
  global:
    secure: AvuDjodpLcBIu/YH7rRqSJySld3Ml4TaL44PpObkHWtQ9N+pGc6k3LjY7p555mjhKrwc5XwZaH+HNe/ClQ7LK2h3wC5Hdodq77ie7d6R7Gh5e2b3U8X/rcliZbNr/T9+2O/01ccY8xblSRAHC4PINiq0Ztfu6np+YG29yEHHtzyA/JNA7XV3U8K0VRybgd/A5qSJFeKW2l9Ur2Wnr4WcB4Q6O8jngUFFZOsy9W69XncK/skEIDU/PM8lq8/DPzs6z+Ww7p//p0a63VDNiYdzTFRb6A2ePgmdtNfbh9ghfrUamNhesBoqplyH3W5BPEGTeB/bLnxWQf8kMCTn3M1w1ilRX2yxFzXvY+UGGUipKWew7jWs5uyAwn6RHfxCxKNS/VphVd8hVBLviarQy/QRDlg09SaMtNq52ZuTnmOydCOLavfKpR90iFVwfDlRxULQceGaOAqsNkpgrdyZFSYr6iKfR5+1qJOGZQT+fIyjH+KLVBiA1Id0KUfsQc2jzb8MB2umfcuy4YkUATnbApQceNFPhoqp0dMJlNLoiVWK32ITkmDZ8JR4lMKihiWaBrmhe7JH1ahugOwzKt2SEuu1kzBdjRJQIHDzAI+781W9I6elQ/UoEJ7uiD2OMq7XD1jxjh9GOXcrFZLm3Lc0kJVr/2NfHnmm0NEhkVhrXKbdaIM=
